"""add threshold_configs table

Revision ID: b43483a47468
Revises: 0001
Create Date: 2026-07-03 22:04:33.430046

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b43483a47468"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threshold_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("instance_id", sa.String(length=255), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("warning_threshold", sa.Float(), nullable=False),
        sa.Column("critical_threshold", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_threshold_configs_instance_id"), "threshold_configs", ["instance_id"], unique=False
    )
    op.drop_constraint(
        op.f("incident_reports_incident_id_fkey"), "incident_reports", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("incident_reports_incident_id_fkey"),
        "incident_reports",
        "incidents",
        ["incident_id"],
        ["incident_id"],
    )
    op.drop_index(op.f("ix_threshold_configs_instance_id"), table_name="threshold_configs")
    op.drop_table("threshold_configs")
    # ### end Alembic commands ###
